### PR TITLE
fix: #116 - return cache-hit=false on partial match hits

### LINKED ISSUE #116: cache-hit output should match actions/cache output
## Bug Report
The gcs-cache-action currently behaves slightly differently than the regular github actions/cache action. According to https://github.com/marketplace/actions/cache#outputs, the cache-hit output only returns true on an exact match hit. I would expect gcs-cache-action to behave the same, but it is currently returning true on exact and partial matches.

## Current behavior
gcs-cache-action is returning cache-hit=true on exact and partial matches.

## Expected behavior
gcs-cache-action should only return cache-hit=true on exact matches like actions/cache does. Partial matches should return cache-hit=false

## Possible Solution

https://github.com/MansaGroup/gcs-cache-action/blob/main/src/main.ts#L169

Should be:
```
core.setOutput('cache-hit', bestMatchKind=='exact');
```
instead of 
```
core.setOutput('cache-hit', 'true');
```
---

**Others:**

### PR DESCRIPTION
**Pull request by coolkev**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (if applicable)
- [ ] Docs have been added / updated (if applicable)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior

gcs-cache-action is returning cache-hit=true on exact and partial matches.

Issue Number fixed #116

## What is the new behavior

gcs-cache-action will only return cache-hit=true on exact matches like actions/cache does. Partial matches will return cache-hit=false

## Does this PR introduce a breaking change

- [x] Yes
- [ ] No

Any workflows that relied on the previous behavior would now think a cache-hit was not found when a partial cache hit was actually restored.

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -141,7 +141,7 @@ async function main() {
       cacheHitKind: bestMatchKind,
       targetFileName: exactFileName,
     });
-    core.setOutput('cache-hit', 'true');
+    core.setOutput('cache-hit', bestMatchKind == 'exact');
```
Comment (jeremylvln) [inline src/main.ts]:
```suggestion
    core.setOutput('cache-hit', bestMatchKind === 'exact');
```

**Review by jeremylvln — CHANGES_REQUESTED** [review]
Use a strict equility and go!

**Review by jeremylvln — APPROVED** [review]
